-- 创建books表
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    price DECIMAL(5, 2),
    category VARCHAR(255)
);

-- 创建shopping_carts表
CREATE TABLE IF NOT EXISTS shopping_carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255)
);

-- 创建shopping_cart_items表
CREATE TABLE IF NOT EXISTS shopping_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_cart FOREIGN KEY (cart_id) REFERENCES shopping_carts (id),
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books (id)
);